### ISSUE TITLE
Include directive for TOML scene files

### ISSUE THREAD

**Issue by dacunni** [dacunni/fluxrt#42]
To simplify TOML scene files with common elements, we need an include directive. This could simply be a tag that indicates other files to include. These would be read in and prepended to the string stream before it is parsed again.

**Comment by dacunni** [comment]
Working now. See TOML examples.

```toml
[[include]]
source = "standard/materials/diffuse-gray-0.7.toml"

[[include]]
source = "standard/scenes/mitsuba-sphere-and-spheres.toml"
```
